name: macOS build

on:
  push:
    branches: [ "main" ]
    tags:     'v*'
    paths-ignore:
      - 'doc/**'
      - '.github/**'
      - '*.md'
  workflow_dispatch:

jobs:

  assets:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4

      - name: pack assets
        run: |
          cd common
          ./ScriptzPacker JellyCram.scriptz *.lua
      
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: JellyCram.scriptz
          path: common/JellyCram.scriptz

  macosNative:
    needs: [assets]
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
          wget https://sdk.lunarg.com/sdk/download/latest/mac/vulkan-sdk.dmg
          hdiutil attach vulkan-sdk.dmg -mountpoint /Volumes/vulkan-sdk
          mkdir ~/vulkan
          cd /Volumes/vulkan-sdk/
          sudo ./InstallVulkan.app/Contents/macOS/InstallVulkan --root ~/vulkan --accept-licenses --default-answer --confirm-command install
          ls ~/vulkan
          cd ~/vulkan/
          python install_vulkan.py

    - name: get assets
      uses: actions/download-artifact@v4
      with:
        name: JellyCram.scriptz

    - name: macos native build
      run: |
        ./build.sh -r -o
        mkdir macosbuild
        cp build/JellyCram/JellyCram macosbuild/
        cp JellyCram.scriptz macosbuild/
        cp LICENSE macosbuild/
        cd macosbuild
        md5sum JellyCam > JellyCam.md5
        md5sum JellyCram.scriptz > JellyCam.md5
        cp READEME.md macosbuild/

    - name: sign build
      run: |
        cd macosbuild
        md5sum JellyCam > JellyCam.md5
        md5sum JellyCram.scriptz > JellyCam.md5

        export GPG_TTY=$(tty)  
        echo "${{ secrets.GPG_KEY }}" > priv
        gpg --pinentry-mode=loopback --passphrase "${{ secrets.GPG_PASS }}" --import priv
        gpg --pinentry-mode=loopback --passphrase "${{ secrets.GPG_PASS }}" -b JellyCam
        gpg --pinentry-mode=loopback --passphrase "${{ secrets.GPG_PASS }}" -b JellyCam.scriptz

    - name: buildArtifact
      uses: actions/upload-artifact@v4
      with:
        name: JellyCram-macos
        path: macosbuild