name: Android build

on:
  push:
    branches: [ "main" ]
    tags:     'v*'
    paths-ignore:
      - 'doc/**'
      - '.github/**'
      - '*.md'
  pull_request:
  workflow_dispatch:

jobs:

  linuxXandroid:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential mesa-common-dev libx11-dev libxrandr-dev libgl1-mesa-dev libglu1-mesa-dev libfreetype6-dev libopenal-dev libsndfile1-dev libudev-dev vulkan-tools libvulkan-dev vulkan-validationlayers-dev spirv-tools
        wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
        unzip android-ndk-r25c-linux.zip
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip   
        unzip commandlinetools-linux-9477386_latest.zip
        export ANDROID_SDK_ROOT=~/
        mv cmdline-tools latest
        mkdir cmdline-tools
        mv latest cmdline-tools
        yes | ./cmdline-tools/latest/bin/sdkmanager --licenses
        ./cmdline-tools/latest/bin/sdkmanager --install "system-images;android-33;google_apis;x86_64"
        ./cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33"
        echo no | ./cmdline-tools/latest/bin/avdmanager create avd --name android33 --package "system-images;android-33;google_apis;x86_64"

    - name: get hop
      run: ./getLibs.sh

    - name: get keystore
      run: |
        export GPG_TTY=$(tty)  
        cd android
        echo "${{ secrets.KEYSTORE }}" > jellycram.jks.asc
        gpg --pinentry-mode=loopback gpg -d --passphrase "${{ secrets.PASS }}"
        rm jellycram.prop
        echo "storePassword=${{ secrets.PASS }}" > jellycram.prop
        echo "keyPassword=${{ secrets.PASS }}" >> jellycram.prop
        echo "storeFile=jellycram.jks" >> jellycram.prop
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> jellycram.prop
        cd ..

    - name: android build
      run: |
        source version.sh
        cd android
        ./gradlew bundleRelease
        cd ..
        mkdir androidbuild
        cp android/app/build/outputs/bundle/release/app-release.aab androidbuild/JellyCram.aab
        cp LICENSE androidbuild/
        cp README.md androidbuild/ 
        rm android/jellycram.prop

    - name: buildArtifact
      uses: actions/upload-artifact@v4
      with:
        name: JellyCram-android
        path: androidbuild