name: JellyCram windows build

on:
  push:
    branches: [ "main" ]
    tags:     'v*'
    paths-ignore:
      - 'doc/**'
      - '.github/**'
  workflow_dispatch:

jobs:

  assets:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3

      - name: pack assets
        run: |
          cd common
          ./ScriptzPacker JellyCram.scriptz *.lua
      
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: JellyCram.scriptz
          path: common/JellyCram.scrtipz

  linuxNative:
    needs: [assets]
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y xorg-dev build-essential mesa-common-dev libx11-dev libxrandr-dev libgl1-mesa-dev libglu1-mesa-dev libfreetype6-dev libopenal-dev libsndfile1-dev libudev-dev g++-mingw-w64-x86-64-posix gcc-mingw-w64-x86-64-posix libxinerama-dev libxcursor-dev vulkan-tools libvulkan-dev vulkan-validationlayers-dev spirv-tools wine64

    - name: get assets
      uses: actions/download-artifact@v3
      with:
        name: JellyCram.scriptz

    - name: windows mingw build
      run: |
        ./build.sh -r -w
        mkdir windowsbuild
        cp build/JellyCram.exe windowsbuild/
        cp JellyCram.scriptz windowsbuild/
        cp build/*.dll windowsbuild/
        cp LICENSE windowsbuild/
        cp READEME.md > windowsbuild

    -name: sign build
      run: |
        cd windowsbuild
        md5sum JellyCam > JellyCam.md5
        md5sum JellyCram.scriptz > JellyCam.md5

        export GPG_TTY=$(tty)  
        echo "${{ secrets.GPG_KEY }}" > priv
        gpg --pinentry-mode=loopback --passphrase "${{ secrets.GPG_PASS }}" --import priv
        gpg --pinentry-mode=loopback --passphrase "${{ secrets.GPG_PASS }}" -b JellyCam
        gpg --pinentry-mode=loopback --passphrase "${{ secrets.GPG_PASS }}" -b JellyCam.scriptz

    - name: buildArtifact
      uses: actions/upload-artifact@v3
      with:
        name: JellyCram-windows
        path: build